# Generated by Django 2.2.10 on 2020-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('count', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('text', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Trigrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('year', models.IntegerField(default=0)),
                ('count', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('text', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Bigrams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('year', models.IntegerField(default=0)),
                ('count', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('text', 'year')},
            },
        ),
    ]
